Registry for OID/Evidence Mappings
lamps-wg/csr-attestation pull request #83
Opened 2024-01-29 11:59 UTC by hannestschofenig

2024-01-29 12:22 UTC, thomas-fossati approved these changes
This seems like a very useful addition.

I am wondering whether the new registry's scope could be extended to cover all typing information related to attestation evidence, including OID, media types, CoAP C-F, CBOR tags, etc., to make this a one-stop shop "meta registry" for everything attestation.
Not sure if there is a precedence for this in IANA.


PS: I have left a couple of markdown-related fixes in-line.

2024-01-29 12:22 UTC, thomas-fossati commented on draft-ietf-lamps-csr-attestation.md
> +~~~
use kramdown-rfc table syntax; also, make reference to TCG a real ref

```suggestion
| OID              | Description                | Reference(s)   | Change Controller |
|------------------|----------------------------|----------------|-------------------|
| 2 23 133 5 4 10  | DICE Evidence              | {{TCGDICE1.1}} |  TCG              |
| 2 23 133 5 4 9   | Conceptual Message Wrapper | {{TCGDICE1.1}} |  TCG              |
{: #tab-ae-reg title="Initial Contents of the Attestation Evidence OID Registry"}
```

2024-01-29 12:22 UTC, thomas-fossati commented on draft-ietf-lamps-csr-attestation.md
> +This section gives an example of extending the ASN.1 module above to carry an existing ASN.1-based evidence statement. The example used is the Trusted Computing Group DICE Attestation Conceptual Mess
```suggestion
This section gives an example of extending the ASN.1 module above to carry an existing ASN.1-based evidence statement. The example used is the Trusted Computing Group DICE Attestation Conceptual Message Wrapper, as defined in {{TCGDICE1.1}}.
```

2024-01-29 12:26 UTC, thomas-fossati commented on draft-ietf-lamps-csr-attestation.md
> +IANA is asked to create a registry that helps developers to find
fix lint error (and clear the CI)

```suggestion
IANA is asked to create a registry that helps developers to find
```

2024-01-29 13:04 UTC, thomas-fossati commented on draft-ietf-lamps-csr-attestation.md
> +
more fix-lint :-)

```suggestion

```

2024-01-29 16:58 UTC, henkbirkholz commented on draft-ietf-lamps-csr-attestation.md
>  - Attest Statement
```suggestion
- Evidence Statement
```
I know, I know... but it would make more sense, right?

2024-01-29 17:01 UTC, henkbirkholz commented on draft-ietf-lamps-csr-attestation.md
>  - Attest Statement
Only occurrence. But if out-of-scope here, this can become a tiny new issue.

2024-01-29 17:25 UTC, henkbirkholz approved these changes

2024-01-29 17:35 UTC, ounsworth commented
Meeting 2024-01-29
This PR is mergeable, pending sorting out the [[TBD]] mail list reference.

2024-01-30 16:28 UTC, ounsworth commented
As per discussion on the RATS mailing list, this is considered a very good idea, and is slipping into scope creep.

At this point, I suggest removing this from the CSR Attestation draft so that the CSR draft is not delayed due to this much larger initiative.

(aka, the CA industry really needs this CSR draft ASAP. Can we please put a New Content Freeze on it?)

https://mailarchive.ietf.org/arch/msg/rats/h98spAElEuQtpIEWStEuaCyRQrI/

2024-01-30 16:34 UTC, henkbirkholz commented
> I am wondering whether the new registry's scope could be extended to cover all typing information related to attestation evidence, including OID, media types, CoAP C-F, CBOR tags, etc., to make this a one-stop shop "meta registry" for everything attestation.
Not sure if there is a precedence for this in IANA.

@thomas-fossati, could you imagine for this endeavor to move into a separate document?

2024-01-30 16:45 UTC, thomas-fossati commented
Sorry, replied to Mike's email before reading this.

> @thomas-fossati, could you imagine for this endeavor to move into a separate document?

Yes, absolutely.

2024-01-30 16:48 UTC, henkbirkholz commented
then we can :ship: this ☺️

2024-01-30 19:20 UTC, mcr commented on draft-ietf-lamps-csr-attestation.md
> +Experts {{RFC8126}}.  However, to allow for the allocation of values
```suggestion
the registration template below after a three-week review period on
the [[TBD]] mailing list, with the advice of one or more Designated
Experts {{RFC8126}}.  However, to allow for the allocation of values
```

I think that it's a three-week review,, *AND* advice of DEs.  With the previous wording, I could interpret "or"

2024-01-30 19:21 UTC, mcr requested changes
As I understand it, we are not asking for a new OID arc, but rather just collecting the OIDs that are used from other arcs?

2024-02-12 17:09 UTC, ounsworth approved these changes

2024-02-12 17:09 UTC, merged